#####################
# BASICS
site_name: Darrell Ross
site_url: https://eukota.github.io
markdown_extensions:
    - smarty
    - meta
    - attr_list
    - md_in_html
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - admonition
    - pymdownx.details

# Quotes uses Admonitions
# https://squidfunk.github.io/mkdocs-material/reference/admonitions/

#####################
# NAV 
nav:
- Home: index.md
- Resume: resume.md
- School: school/degrees.md
- Personal:
    - Bands: personal/bands.md
    - Instruments: personal/instruments.md
    - Origami: personal/origami.md
    - Bubbles: personal/bubbles.md
    - Gardening: personal/gardening.md
    - Family: personal/family.md
- Sites: sites/sites.md
- Engineering:
    - UCSC Courses: engineering/ucsc_courses.md
    - HSU Courses: engineering/hsu_courses.md
    - UW Courses: engineering/uw_courses.md
    - Training: engineering/training.md
    - Scrum Framework: engineering/scrum_framework.md
    - Scrum Framework Minimums: engineering/scrum_framework_minimums.md
    - LaTeX: engineering/latex.md
    - Water Tank Meter: engineering/water_tank_meter.md
    - Microbit: engineering/microbit.md
    - Circuit Playground: engineering/circuit_playground.md
    - Electronics Workbench: engineering/workbench.md
    - MkDocs: engineering/mkdocs.md
    - Markdown Cheatsheet: engineering/markdown_sample.md
- Intentional Documentation:
    - Intentional Documentation: documentation/intentional_documentation.md
    - Per Page:
        - Page Tree: documentation/per_page/page_tree.md
        - Table of Contents: documentation/per_page/toc.md
        - TOC Driven Documentation: documentation/per_page/toc_driven.md
        - Reviews: documentation/per_page/reviews.md
    - Per Project: 
        - Page Style Guide: documentation/per_project/page_style_guide.md
        - Audience Page Map: documentation/per_project/audience_page_map.md
        - Support Feedback Loop: documentation/per_project/support_feedback_loop.md
        - Curators: documentation/per_project/curators.md
    - Patterns: documentation/patterns.md
    - Antipatterns: documentation/antipatterns.md

#####################
# THEME
theme:
    name: material
    #custom_dir: docs/material

    # 404 page
    static_templates:
        - 404.html

    # Necessary for search to work properly
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml, necessary for github pages deployment
    language: en
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/images/favicon.png
    icon:
        logo: logo
    palette:
        - scheme: default
          primary: deep purple
          accent: green
          toggle:
            icon: material/toggle-switch-off-outline 
            name: Switch to dark mode
        - scheme: slate 
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode

    # Additional Values
    features:
        - navigation.instant
        - navigation.tracking
        - toc.follow
        #- toc.integrate
        - navigation.top

#####################
# EXTRAS
use_directory_urls: false # enabled the direct html link for the Guntley PV Barn
extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/darrellaross/
        - icon: fontawesome/brands/github
          link: https://www.github.com/eukota

#####################
# PLUGINS
plugins:
    - search
    - glightbox
    #- table-reader
