#####################
# BASICS
site_name: Darrell Ross
site_url: https://eukota.github.io
markdown_extensions:
    - smarty
    - meta

#####################
# NAV 
nav:
- Home: index.md
- Resume: resume.md
- School: school/degrees.md
- Personal:
    - Bands: personal/bands.md
    - Instruments: personal/instruments.md
    - Origami: personal/origami.md
    - Bubbles: personal/bubbles.md
    - Gardening: personal/gardening.md
    - Family: personal/family.md
- Sites: sites/sites.md
- Engineering:
    - UCSC Courses: engineering/ucsc_courses.md
    - HSU Courses: engineering/hsu_courses.md
    - UW Courses: engineering/uw_courses.md
    - LaTeX: engineering/latex.md
    - MkDocs: engineering/mkdocs.md
    - Markdown Cheatsheet: engineering/markdown_sample.md

#####################
# THEME
theme:
    name: material
    #custom_dir: docs/material

    # 404 page
    static_templates:
        - 404.html

    # Necessary for search to work properly
    include_search_page: false
    search_index_only: true

    # Default values, taken from mkdocs_theme.yml, necessary for github pages deployment
    language: en
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/images/favicon.png
    icon:
        logo: logo
    palette:
        - scheme: default
          primary: deep purple
          accent: green
          toggle:
            icon: material/toggle-switch-off-outline 
            name: Switch to dark mode
        - scheme: slate 
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode

    # Additional Values
    features:
        - navigation.instant
        - navigation.tracking
        - toc.follow
        #- toc.integrate
        - navigation.top

#####################
# EXTRAS
use_directory_urls: false # enabled the direct html link for the Guntley PV Barn
extra:
    social:
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/darrellaross/
        - icon: fontawesome/brands/github
          link: https://www.github.com/eukota

#####################
# PLUGINS
plugins:
    - search
